### ISSUE TITLE
PW Dependecy

### ISSUE THREAD

**Issue by pmichaelis** [Toutouwai/ConnectPageFields#4]
Hey, I just noticed, that the processwire dependecy is 3.0.1.66, but the current master is 3.0.165. 
Does the module require the actual dev bracnh?

`'requires' => 'ProcessWire>=3.0.166, PHP>=5.4.0',`

**Comment by Toutouwai** [comment]
Yes, the current version (0.3.2) requires 3.0.166 because prior to 3.0.166 the PW core was affected by this bug: https://github.com/processwire/processwire-issues/issues/572

If you want to install the module on an older version of PW you'll need ConnectPageFields v0.3.1 which works around the bug to some extent: https://github.com/Toutouwai/ConnectPageFields/tree/99f5e06b959d100a57ab130fa6e6f57ffea19dc9
